---
title: "text_study_1"
output: html_document
---

# Herzlich Willkommen

Herzlich willkommen zu meiner Shiny-App!


Im Rahmen meiner Masterarbeit *Messfehlerbehaftete Daten: Ein Vergleich zwischen 
linearer Regression und Strukturgleichungsmodellen* habe ich eine
Shiny-Webapplikation programmiert. Diese soll die Auswirkungen messfehlerbehafteter 
Daten auf die Regressionsgerade aufgezeigen sowie ein Vergleich zum 
Strukturgleichungsmodell (engl. *structural equation modeling*, SEM) mit Hinblick 
auf die in zwei Monte-Carlo-Simulationen untersuchten Grössen ermöglichen.
Durch die Webapplikation können auch Ergebnisse von Versuchsbedingungen betrachtet 
werden, die in der schriftlichen Arbeit nicht gezeigt wurden. 

# Überblick

Auf der linken Seite befindet sich die Navigationsleiste, welche sich in folgende
Bereiche aufteilt:

* Intro
* Studie 1
* Studie 2

Das **Intro** bietet eine leicht verständliche Einführung in die theoretischen
Grundlagen der linearen Einfachregression sowie von SEMs. In einer interaktiven
Applikation können die Auswirkungen messfehlerbehafteter Daten beim Einsatz von 
einfachen linearen Regressionsmodellen beobachtet werden.
In den Kapiteln zu **Studie 1** sowie **Studie 2** können die beiden
Monte-Carlo-Simulationen inklusive deren Resultate eingesehen werden. In der
schriftlichen Arbeit wurde auf die Präsentation der Ergebnisse für einen Grossteil
der Versuchsbedingungen aus Platzgründen verzichtet. Das Shiny-App ermöglicht es
Interessenten nun, die Ergebnisse sämtlicher Versuchsbedingungen zu studieren.

Ich wünsche viel Spass!