---
output: html_fragment
---

Messfehlerfreie Daten bilden eine zentrale Voraussetzung für den Einsatz der linearen Einfachregression. Zufällige Messfehler können sowohl in der *unabhängigen Variable* (UV) als auch der *abhängigen Variable* (AV) auftreten. Dabei sinkt die Reliabilität der UV und AV, je grösser die Messfehler ausfallen. Umgekehrt bedeutet eine perfekte Reliabilität von 1.0, dass die jeweilige Variable frei von Messfehlern ist.

Im Panel links können die Reliabilitäten für die UV und AV sowie die Stichprobengrösse angepasst werden. Nach einem Klick auf den Button werden Daten mit den entsprechenden Eigenschaften generiert. Im Anschluss wird eine lineare Einfachregression an die generierten Daten angepasst. Die Ergebnisse dieses Regressionsmodells sind im rechten Panel einsehbar. Dieses zeigt im ersten Tab eine grafische Darstellung des Regressionsmodells:

* Scatterplot der generierten Daten
* geschätzte Regressionsgerade als durchgezogene Linie in Rot
* 95%-Konfidenzintervall als graues Band um die geschätzte Regressionsgerade
* wahre Regressionsgerade als gestrichelte Linie in Grau 

Mit einem Klick auf das Zahnrad-Symbol `r icon::fa("cogs")` oben rechts können die Grenzen der x- sowie y-Achse angepasst werden. 

Das zweite Tab beinhaltet den Output des Regressionsmodells durch R mit den dazugehörigen Kennzahlen. Besonders interessant sind hier die Spannweite der Residuen, die Schätzungen des Regressionskoeffizienten $\beta_1$ sowie dessen Standardfehler, der Determinationskoeffizient $R^2$ sowie die F-Statistik. Deren Verhalten zeigt eindeutig, dass bei einer geringen Reliabilität der UV $\beta_1$ falsch geschätzt wird, während eine messfehlerbehaftete AV im Mittel zu korrekten Schätzungen mit grösserer Unsicherheit führt. 